### ISSUE TITLE
Import account not existed hang forever

### ISSUE THREAD

**Issue by vince8x** [bcProFoundation/AbcPay#81]
Steps:
- Import a new account (not existed)
- Click on "Go back" option
- Expected: back to the create account screen
- Actual: the import screen hangs forever

![image](https://user-images.githubusercontent.com/236093/180914126-ca79712b-6013-45fe-9e11-9d98743ae8ec.png)

![image](https://user-images.githubusercontent.com/236093/180914115-c77496fe-03e2-4aae-ba35-2dd9d6593a31.png)

**Comment by kensauruss** [comment]
This fixed in the new release @vince8x pls check again.

@eric-son12 FYI
